dist: xenial
language: python
python:
  - '3.7'
install:
  - 'pip install pipenv'
  - 'pipenv install'
script: 'python -m pytest --cov=cotuong tests --cov-report=xml'
after_success:
  - 'python-codacy-coverage -r coverage.xml'